### PR TITLE
My fix j query watermark

### PR DESCRIPTION
**Pull request by jkeath**
Hi,
I put the wrap statement back into the code.
I used the same logic as your width fix by adding a check for data-percent-height.  I added that attribute to each of my inputs and it works.  Please test.

This is the code I added
if ($elem.attr('data-percent-height') == 'true')
                watermark_container.css('height', '100%');

### CODE REVIEW

**Comment by marioestrada** [comment]
I'll look into it, the thing is imagine someone sets the height to 50% I'm not sure if this patch would work.

**Comment by jkeath** [comment]
yeah i see your point, wouldn't that same logic apply to your width fix?

**Comment by marioestrada** [comment]
Thinking about it, I believe this will make it work as expected. Merging, thanks.

**Comment by jkeath** [comment]
no problem, glad I could help.  This is by far the best watermark widget I have found and we are using it in our app.  We like to avoid using widgets and changing them ourselves so that we are always able to follow the upgrade path as new versions get released which is why I was hoping to work with you for  fix for the issue I was having.  I'll watch for your next release.

Thanks again for your hard work and effort putting together such a nice widget.

**Pull request merged**
