### PR TITLE
Update jquery.watermark.js

### PR DESCRIPTION
**Pull request by jkeath**
Please test and incorporate into plugin if you feel it satisfactorly solves issues with height and width of input elements being altered when they were set via percentages

### CODE REVIEW

**Comment by marioestrada** [comment]
Are you sure it solves your issues? I tested it and the plugin stopped working.

This is what the demo page looks like with the changes you sent: http://cl.ly/0d3L1c03331g2V3I053Y

Just by looking at the code I knew it would not work, the wrap function is totally necessary for the watermark to work.

**Comment by jkeath** [comment]
yeah it totally solves the issue.  If what you are doing with the wrap() function is to add a custom attribute to the input elements than, no it's no needed at all.  The code I put in does exactly the same thing except it doesn't jack up the height and width of the input element.   I did notice that the watermark text in my case was floating a litte below the input element's so I adjusted the Top option and it works.  Maybe I just don't understand what that wrap function is doing for you.  If that is indeed needed than the solution is to simply apply some more logic similiar to your width fix but for the height as well.

**Comment by marioestrada** [comment]
**It does not solve the issue, try it with various text input elements on a single page it will not work.** Did you take a look at the screen I sent you, compare it with http://labs.mario.ec/jq-watermark/

I don't use the wrap function to add attributes to the input element, I use the wrap function to actually add the elements to the page and making it possible for the watermark/placeholder to be placed so that it appears to be inside the input, for the way I implemented the plugin **the wrap function is 100% necessary**, believe me I wrote it.

Yes the fix might be similar to what I implemented for the width issue, I'll take a look at it when I have some spare time.

**Comment by jkeath** [comment]
odd it works perfectly in our app, we have 3 different inputs on the same page all using this and it works.

**Comment by jkeath** [comment]
I can try implementing the fix using your method and add the one with the height, if it works ill issue another pull request

**Comment by marioestrada** [comment]
Depending on how your form is formed it might look like it works, for example if you have your input inside table columns or divs with `position: relative` otherwise it won't work as you can see from the screen I posted earlier.

**Pull request closed without merging**
